/**
 * Topic-based study plan groupings, layered on top of PRECEPT_TOPICS (see precepts.ts).
 * Compiled from "Study Plans by Category" and "Weekly Study Plan" (Precept Upon Precept — Tobiah Israel).
 *
 * Every entry here references an existing PRECEPT_TOPICS `key` rather than duplicating
 * verse/note data, so precepts.ts remains the single source of truth for topic content.
 */

/** One of 12 broad life-topic groupings, each holding an ordered list of topic keys. */
export interface StudyPlanCategory {
  id: string;
  title: string;
  description: string;
  topicKeys: string[];
}

export const STUDY_PLAN_CATEGORIES: StudyPlanCategory[] = [
  {
    id: "identity-heritage",
    title: "Identity & Heritage of Israel",
    description: "Who Israel is, Israel's calling, nationality, and heritage.",
    topicKeys: [
      "called",
      "chosen",
      "color",
      "color-range-of-israel",
      "confusion-of-faces",
      "dogs-heathen-nations",
      "elect",
      "gentiles-israel-called-gentiles",
      "gentiles-other-nations",
      "grace",
      "grace-does-not-give-license-to-sin",
      "grace-what-is",
      "heathen-not-justified",
      "israel-above-all-nations",
      "israel-called-the-church",
      "israel-christ-only-came-for",
      "israel-disconnected-from-heritage",
      "israel-elect",
      "israel-foreknew",
      "israel-gods-heritage",
      "israel-gods-law-was-given-to",
      "israel-in-americas",
      "israel-justified",
      "israel-kingdom-of-priest",
      "israel-name-changed",
      "israel-not-dealing-with-judah",
      "israel-prince",
      "israel-repentance",
      "israel-salvation",
      "israel-the-lords-portion",
      "israel-what-god-requires",
      "israel-whole-world-belongs-to",
      "israelites-referred-to-as-angels",
      "israelites-called-gentiles-heathens-strangers",
      "israelites-lived-in-egypt-in-the-new-testament",
      "israelites-lived-in-rome",
      "israelites-prophets-are-israelites",
      "james-talked-to-12-tribes-of-israel",
      "jews-believed-in-christ",
      "just-in-the-eyes-of-god",
      "nationality-of-the-samaritan-woman-in-john-4",
      "nationality-race",
      "natural-gentiles",
      "real-gentile-nations",
      "real-jews",
      "sealed",
      "separated-nations",
      "strangers-other-nations",
      "zion",
    ],
  },
  {
    id: "nature-of-god-and-christ",
    title: "The Nature of God & Christ",
    description: "The character of God and the identity, work, and return of Christ.",
    topicKeys: [
      "another-jesus",
      "christ-came-for-israel",
      "christ-did-not-baptize-with-water",
      "christ-freed-us-from-the-law-of-sin-and-death",
      "christ-from-the-tribe-of-judah",
      "christ-fulfilled",
      "christ-had-an-earthly-father",
      "christ-in-roman-captivity",
      "christ-in-the-apocrypha",
      "christ-in-the-old-testament",
      "christ-is-not-the-father",
      "christ-justifies-israel-only",
      "christ-return",
      "christ-taught-repentance",
      "christ-told-us-not-to-sin",
      "christ-was-not-soft",
      "christ-who-rejected-him",
      "color-of-christ",
      "fallen-angels",
      "foreknew-god",
      "god-dealing-with-the-mixed-multitude",
      "god-does-evil",
      "god-does-have-respect-of-persons",
      "god-does-not-hear-sinners",
      "god-gives-recompense-and-revenge",
      "god-hates",
      "god-is-a-man",
      "god-is-black",
      "god-loves-israel",
      "god-must-deal-with-the-southern-judah-kingdom-first",
      "god-pleads-with-the-nations",
      "god-puts-difference-between-the-children-of-israel-and-ham",
      "gods-favorites",
      "gods-people",
      "gods-way-question-him",
      "holy-ghost",
      "holy-spirit",
      "how-do-we-know-that-we-know-god",
      "jesus-had-a-home",
      "jesus-means",
      "manner-of-christ",
      "name-of-god",
    ],
  },
  {
    id: "law-and-commandments",
    title: "The Law & Commandments",
    description: "The commandments, dietary laws, circumcision, and how the Law applies.",
    topicKeys: [
      "abraham-kept-the-laws",
      "circumcision",
      "circumcision-of-heart",
      "clean",
      "clean-food",
      "cleanse",
      "dietary-laws",
      "eat-sacrifice",
      "keep-the-commandments",
      "keeping-laws-in-present-world",
      "law-and-commandment-the-same",
      "law-not-void-through-our-faith",
      "laws-from-the-beginning",
      "laws-of-the-land",
      "no-commandments-no-kingdom",
      "sacrificial-law-is-dead",
      "sex-laws",
      "sex-with-your-wife-when-she-is-on-her-issue-of-blood",
      "teaching-children-commandments",
      "the-law",
      "tithe",
    ],
  },
  {
    id: "high-holy-days-and-feasts",
    title: "High Holy Days & Feasts",
    description: "The appointed feasts, the Sabbath, and the sacred calendar.",
    topicKeys: [
      "day-of-atonement",
      "high-holy-days-day-of-atonement",
      "feast-of-dedication",
      "feast-of-tabernacles",
      "high-holy-days",
      "high-holy-days-feast-of-tabernacles",
      "high-holy-days-memorial-of-blowing-of-trumpets",
      "high-holy-days-new-moon",
      "high-holy-days-passover",
      "high-holy-days-pentecost",
      "high-holy-days-purim",
      "sabbath",
      "months-comes-from-moon",
      "moon-does-not-dictate-sabbath",
      "new-moon-does-not-determine-the-sabbath",
      "high-holy-days-feast-of-dedication",
    ],
  },
  {
    id: "sin-repentance-and-salvation",
    title: "Sin, Repentance & Salvation",
    description: "Sin, repentance, grace, and salvation.",
    topicKeys: [
      "abortion",
      "adultery",
      "born-again",
      "born-gay",
      "cover-up-sin",
      "homosexual-gay",
      "john-told-us-not-to-sin",
      "lust",
      "new-creature",
      "paul-told-us-not-to-sin",
      "rape-is-a-sin",
      "regeneration",
      "repent-or-die",
      "repentance-according-to-the-bible",
      "repentance-is-only-for-israel",
      "salvation-for-israel",
      "sexual-sins",
      "show-our-people-their-sins",
      "sickness-from-sin-and-healing",
      "sin",
      "sinner",
      "sodom-spirit",
      "solomons-sin",
      "wages-of-sin",
      "whoredom-physical",
      "whoredom-spiritual",
    ],
  },
  {
    id: "family-marriage-and-gender-roles",
    title: "Family, Marriage & Gender Roles",
    description: "Marriage, family life, and the roles of men and women.",
    topicKeys: [
      "adoption",
      "birth-of-a-boy",
      "birth-of-a-girl",
      "children-raising-kids",
      "daughters",
      "divorce",
      "family-according-to-the-bible",
      "firstborn-heir",
      "good-wife",
      "interracial-marriage",
      "labor-pains-were-created",
      "man-must-rule-his-household",
      "man-show-thyself-a-man",
      "marriage",
      "marriage-papers",
      "marriage-to-other-nations",
      "marriageable-age",
      "men-need-to-work",
      "multiple-wives",
      "order-of-man-and-woman",
      "order-of-women",
      "seed-comes-from-the-man",
      "take-wives-and-build-a-nation",
      "wicked-women",
      "woman-cannot-divorce-her-husband",
      "woman-must-submit-to-husband",
      "woman-learn-from",
    ],
  },
  {
    id: "personal-holiness-and-appearance",
    title: "Personal Holiness & Appearance",
    description: "Dress, hair, and outward conduct as expressions of holiness.",
    topicKeys: [
      "apparel",
      "appearance",
      "beard",
      "blonde-hair-is-unclean",
      "braids",
      "dress-code-for-women",
      "dress-code-fringes",
      "earrings",
      "eyes-red-with-wine",
      "hair-texture",
      "head-covering-men",
      "head-covering-women",
      "how-to-dress",
      "known-by-his-look",
      "linen-breeches",
      "loin-gird-up",
      "long-hair-men",
      "purple-royalist",
      "strange-apparel",
      "tattoos",
      "women-cant-wear-pants",
      "modesty-dress",
      "wooly-hair",
    ],
  },
  {
    id: "false-teachings-and-other-religions",
    title: "False Teachings & Other Religions",
    description: "Discernment regarding false doctrine and other religious traditions.",
    topicKeys: [
      "catholicism",
      "christmas-is-not-of-christ",
      "fake-jews-jewish",
      "false-christ",
      "false-prophet",
      "idolatry",
      "images-changed",
      "images-goodly",
      "images-worship",
      "immaculate-conception-lie",
      "infidel",
      "islam-created-in-622-ad",
      "koran",
      "rasta",
      "spells-and-enchantments-on-jacob",
      "spiritual-idolatry",
      "trinity",
      "true-witness-jehovah-witness",
      "ufo-ufos-are-chariots",
      "witch-witchcraft-magic-star-gazing",
    ],
  },
  {
    id: "history-captivity-and-prophecy",
    title: "History, Captivity & Prophecy",
    description: "Israel's history — captivity, slavery, and related prophecy.",
    topicKeys: [
      "atrocities-only-to-israel",
      "color",
      "caesar-borgia",
      "captivity",
      "colonization",
      "destruction",
      "destruction-of-nicanor",
      "destruction-of-the-spirit",
      "egyptologist",
      "esau",
      "esau-birth-of",
      "esau-birthright",
      "esau-blessings",
      "esau-border-of-wickedness",
      "esau-called-edom",
      "esau-descendants",
      "esau-driven-away",
      "esau-edom-macedonians-greeks-are-edomites",
      "esau-edom-shall-go-into-captivity",
      "esau-for-violence-against-judah",
      "esau-is-evil-enemy",
      "esau-judgment-on-edom",
      "esau-makes-laws-to-benefit-themselves",
      "esau-pride",
      "esau-white-wash-the-bible",
      "giants",
      "herod",
      "israel-in-slavery",
      "israel-migration-of-10-tribes",
      "israel-would-go-into-captivity-on-slave-ships",
      "israelites-built-pyramids",
      "israelites-will-be-scattered",
      "judah-and-israel-would-be-oppressed-together",
      "moses-age-when-he-left-egypt-the-first-time",
      "moses-came-down-with-more-than-just-ten-commandments",
      "motherland",
      "mount-seir",
      "nations-in-captivity",
      "northern-kingdom-coming-to-america",
      "northern-kingdom-in-jerusalem",
      "northern-kingdom-skin-color",
      "oppression",
      "paul-mistaken-for-an-egyptian",
      "sanctuary-in-captivity",
      "scattered-among-nations",
      "slavery",
      "star-of-david",
      "wicked-nation-esau",
      "concentration-camps",
      "esau-god-hates",
      "northern-kingdom-not-a-people",
    ],
  },
  {
    id: "israelite-character-and-conduct",
    title: "Israelite Character & Conduct (Moral & Civil Laws)",
    description: "Everyday Israelite character, moral conduct, and civil law.",
    topicKeys: [
      "abomination-abominable",
      "actions",
      "adam-sons-of-god",
      "agree-agreement",
      "alms-giving",
      "angels-protecting-us",
      "anger-angry",
      "ark-of-the-covenant",
      "army",
      "assimilation",
      "avenge",
      "baptism",
      "basic-necessities",
      "be-quiet",
      "beasts",
      "begin-with-milk",
      "believe-believing",
      "birthdays",
      "blindness",
      "blood-against-blood",
      "body-must-be-on-one-accord",
      "books-many",
      "breath-of-life",
      "brother-according-to-the-bible",
      "brotherhood",
      "brotherly-covenant",
      "brotherly-love-and-charity",
      "call-upon",
      "chastisement",
      "christians",
      "church",
      "comfort",
      "commandments-and-faith-of-christ",
      "contentment",
      "conversation",
      "convert",
      "correction",
      "covenants-are-with-israel",
      "crafty-counsel",
      "darkness",
      "daughter-or-babylon",
      "devout",
      "division",
      "dont-worry",
      "drunkards",
      "enemies-ensign",
      "enemies-death",
      "enemy",
      "enemy-to-god",
      "envy",
      "evil",
      "evil-communications",
      "evil-angels-spirit-satan",
      "faith-without-works-is-dead",
      "fasting",
      "fear-not-men",
      "fear-the-lord",
      "field",
      "flee-babylon",
      "fool",
      "gang-bangers",
      "glory",
      "good-according-to-the-bible",
      "good-doctrine",
      "gossip-busybody-and-tale-bearing",
      "haste",
      "hate",
      "hatred",
      "heart",
      "heart-mind-understanding",
      "horn",
      "how-a-nation-should-be-ran",
      "how-god-feels-about-the-other-nations",
      "how-to-read",
      "hypocrite",
      "instruction",
      "jesting-scorning-and-mocking",
      "laziness-idleness",
      "leprosy",
      "light",
      "live-what-makes-us-live",
      "love",
      "love-of-god",
      "lying",
      "lying-pastors",
      "meek",
      "milk",
      "neighbor",
      "new-testament-only-for-israel",
      "obedience-obey",
      "olive-tree",
      "order",
      "order-decently-and-in-order",
      "our-names-changed",
      "our-profession",
      "out-of-order",
      "patience",
      "pauls-writings-are-laws",
      "perfection",
      "plead-sword-war",
      "prayer",
      "praying-in-the-streets",
      "produce-your-cause",
      "proud-and-pride-be-humble",
      "rebellious-stubborn",
      "rebuke-reproof-and-correction",
      "righteousness",
      "saints",
      "seek",
      "slander",
      "smoking",
      "sober",
      "sovereign",
      "speak-boldly",
      "speak-smooth-things",
      "spirit",
      "spiritual",
      "spiritually-dead",
      "sports",
      "storms",
      "swearing-snitching",
      "sword",
      "table",
      "tarry-not",
      "temptation",
      "traditions-and-pagan-holidays",
      "trust-in-man",
      "understanding",
      "understanding-and-wisdom",
      "virgin",
      "voting",
      "way-the-way",
      "we-go-to-our-enemies-for-all-of-our-needs",
      "god-hates",
      "christ-who-rejected-him",
      "whole-duty-of-man",
      "whosoever",
      "wicked-imaginations",
      "will-of-god",
      "wisdom",
      "wont-listen",
      "work-works",
      "world",
    ],
  },
  {
    id: "end-times-and-judgment",
    title: "End Times & Judgment",
    description: "Judgment, the last days, and the hereafter.",
    topicKeys: [
      "book-of-life",
      "book-of-the-dead",
      "bottomless-pit",
      "eternal-life",
      "heaven",
      "heaven-how-to-get-in",
      "hell",
      "judge-we-can-judge",
      "mark-of-the-beast",
      "tribulation",
    ],
  },
  {
    id: "understanding-and-studying-scripture",
    title: "Understanding & Studying Scripture",
    description: "How to read, understand, and study the Bible itself.",
    topicKeys: [
      "all-knowledge-given-to-israel",
      "bible-author",
      "how-to-read",
      "bible-only-for-israel",
      "bible-true-book",
      "dark-sayings-and-parables",
      "doctrine",
      "knowledge",
      "prove",
      "pure-language",
      "study",
      "study-whole-bible",
      "the-names",
      "tongues",
      "truth",
      "who-wrote-the-bible",
      "word-word-is-pure",
    ],
  },
];

/** One week of the 14-phase weekly study plan. */
export interface WeeklyStudyWeek {
  week: number;
  topicKeys: string[];
}

/** One of 14 phases in the weekly study plan, paced into weeks by scripture-reference volume. */
export interface WeeklyStudyPhase {
  id: string;
  title: string;
  description: string;
  startWeek: number;
  endWeek: number;
  weeks: WeeklyStudyWeek[];
}

export const WEEKLY_STUDY_PLAN: WeeklyStudyPhase[] = [
  {
    id: "identity",
    title: "Identity",
    description: "Who Israel is, Israel's calling, nationality, and heritage.",
    startWeek: 1,
    endWeek: 9,
    weeks: [
      { week: 1, topicKeys: ["color", "caesar-borgia"] },
      { week: 2, topicKeys: ["called", "chosen", "color-range-of-israel", "confusion-of-faces", "dogs-heathen-nations"] },
      { week: 3, topicKeys: ["egyptologist", "elect", "gentiles-israel-called-gentiles", "gentiles-other-nations"] },
      { week: 4, topicKeys: ["giants", "grace", "grace-does-not-give-license-to-sin", "grace-what-is", "heathen-not-justified", "herod", "israel-above-all-nations"] },
      { week: 5, topicKeys: ["israel-called-the-church", "israel-christ-only-came-for", "israel-disconnected-from-heritage", "israel-elect", "israel-foreknew", "israel-gods-heritage", "israel-gods-law-was-given-to"] },
      { week: 6, topicKeys: ["israel-in-americas", "israel-justified", "israel-kingdom-of-priest", "israel-name-changed", "israel-not-dealing-with-judah", "israel-prince", "israel-repentance", "israel-salvation", "israel-the-lords-portion", "israel-what-god-requires", "israel-whole-world-belongs-to", "israelites-referred-to-as-angels", "israelites-built-pyramids"] },
      { week: 7, topicKeys: ["israelites-called-gentiles-heathens-strangers", "israelites-lived-in-egypt-in-the-new-testament", "israelites-lived-in-rome", "israelites-prophets-are-israelites", "james-talked-to-12-tribes-of-israel", "jews-believed-in-christ", "just-in-the-eyes-of-god", "moses-age-when-he-left-egypt-the-first-time", "moses-came-down-with-more-than-just-ten-commandments", "nationality-of-the-samaritan-woman-in-john-4"] },
      { week: 8, topicKeys: ["nationality-race", "natural-gentiles", "paul-mistaken-for-an-egyptian", "real-gentile-nations", "real-jews", "sealed", "separated-nations"] },
      { week: 9, topicKeys: ["star-of-david", "strangers-other-nations", "zion"] },
    ],
  },
  {
    id: "oppression",
    title: "Oppression",
    description: "The historical oppression endured by Israel.",
    startWeek: 10,
    endWeek: 11,
    weeks: [
      { week: 10, topicKeys: ["atrocities-only-to-israel", "destruction", "destruction-of-nicanor"] },
      { week: 11, topicKeys: ["destruction-of-the-spirit", "judah-and-israel-would-be-oppressed-together", "oppression"] },
    ],
  },
  {
    id: "slavery",
    title: "Slavery",
    description: "Captivity, bondage, and the scattering into slavery.",
    startWeek: 12,
    endWeek: 14,
    weeks: [
      { week: 12, topicKeys: ["captivity", "israel-in-slavery", "israel-migration-of-10-tribes", "israel-would-go-into-captivity-on-slave-ships", "israelites-will-be-scattered", "motherland"] },
      { week: 13, topicKeys: ["nations-in-captivity", "northern-kingdom-coming-to-america", "northern-kingdom-in-jerusalem", "northern-kingdom-skin-color", "sanctuary-in-captivity", "scattered-among-nations", "slavery"] },
      { week: 14, topicKeys: ["concentration-camps", "northern-kingdom-not-a-people"] },
    ],
  },
  {
    id: "colonialism",
    title: "Colonialism",
    description: "Esau/Edom and the colonizing power set against Israel.",
    startWeek: 15,
    endWeek: 17,
    weeks: [
      { week: 15, topicKeys: ["colonization", "esau", "esau-birth-of", "esau-birthright", "esau-blessings", "esau-border-of-wickedness", "esau-called-edom", "esau-descendants", "esau-driven-away"] },
      { week: 16, topicKeys: ["esau-edom-macedonians-greeks-are-edomites", "esau-edom-shall-go-into-captivity", "esau-for-violence-against-judah", "esau-is-evil-enemy", "esau-judgment-on-edom", "esau-makes-laws-to-benefit-themselves", "esau-pride", "esau-white-wash-the-bible", "mount-seir"] },
      { week: 17, topicKeys: ["wicked-nation-esau", "esau-god-hates"] },
    ],
  },
  {
    id: "moral-law",
    title: "Moral Law",
    description: "The ethical commands — character, virtue, and personal conduct.",
    startWeek: 18,
    endWeek: 42,
    weeks: [
      { week: 18, topicKeys: ["abomination-abominable", "abraham-kept-the-laws", "actions", "adam-sons-of-god", "agree-agreement"] },
      { week: 19, topicKeys: ["alms-giving", "angels-protecting-us", "anger-angry", "assimilation"] },
      { week: 20, topicKeys: ["avenge", "basic-necessities", "be-quiet"] },
      { week: 21, topicKeys: ["beasts", "begin-with-milk", "believe-believing", "birthdays"] },
      { week: 22, topicKeys: ["blindness", "body-must-be-on-one-accord", "books-many", "breath-of-life", "brother-according-to-the-bible", "brotherhood", "brotherly-covenant"] },
      { week: 23, topicKeys: ["brotherly-love-and-charity", "call-upon", "chastisement"] },
      { week: 24, topicKeys: ["christians", "church", "circumcision-of-heart", "comfort", "commandments-and-faith-of-christ"] },
      { week: 25, topicKeys: ["contentment", "conversation", "convert", "correction", "covenants-are-with-israel", "crafty-counsel", "darkness"] },
      { week: 26, topicKeys: ["daughter-or-babylon", "devout", "division", "dont-worry", "drunkards", "enemies-ensign", "enemies-death"] },
      { week: 27, topicKeys: ["enemy", "enemy-to-god", "envy", "evil", "evil-communications"] },
      { week: 28, topicKeys: ["evil-angels-spirit-satan", "faith-without-works-is-dead", "fasting"] },
      { week: 29, topicKeys: ["fear-not-men", "fear-the-lord", "field", "flee-babylon", "fool", "glory", "good-according-to-the-bible", "good-doctrine"] },
      { week: 30, topicKeys: ["gossip-busybody-and-tale-bearing", "haste", "hate", "hatred"] },
      { week: 31, topicKeys: ["heart", "heart-mind-understanding", "horn", "how-god-feels-about-the-other-nations", "how-to-read", "hypocrite"] },
      { week: 32, topicKeys: ["instruction", "jesting-scorning-and-mocking", "laziness-idleness", "leprosy"] },
      { week: 33, topicKeys: ["light", "live-what-makes-us-live", "love", "love-of-god"] },
      { week: 34, topicKeys: ["lying", "lying-pastors", "meek", "milk", "neighbor", "new-testament-only-for-israel", "obedience-obey"] },
      { week: 35, topicKeys: ["olive-tree", "our-names-changed", "our-profession", "patience", "pauls-writings-are-laws", "perfection"] },
      { week: 36, topicKeys: ["prayer", "praying-in-the-streets", "produce-your-cause", "proud-and-pride-be-humble"] },
      { week: 37, topicKeys: ["rebellious-stubborn", "rebuke-reproof-and-correction", "righteousness"] },
      { week: 38, topicKeys: ["saints", "seek", "slander", "smoking"] },
      { week: 39, topicKeys: ["sober", "speak-boldly", "speak-smooth-things", "spirit", "spiritual", "spiritually-dead", "sports", "storms", "tarry-not", "temptation"] },
      { week: 40, topicKeys: ["trust-in-man", "understanding", "understanding-and-wisdom", "virgin", "way-the-way", "we-go-to-our-enemies-for-all-of-our-needs", "god-hates", "christ-who-rejected-him", "whole-duty-of-man"] },
      { week: 41, topicKeys: ["whosoever", "wicked-imaginations", "will-of-god", "wisdom"] },
      { week: 42, topicKeys: ["wont-listen", "work-works", "world"] },
    ],
  },
  {
    id: "civil-law",
    title: "Civil Law",
    description: "Governance, national order, and civil justice.",
    startWeek: 43,
    endWeek: 46,
    weeks: [
      { week: 43, topicKeys: ["army", "blood-against-blood", "gang-bangers", "how-a-nation-should-be-ran"] },
      { week: 44, topicKeys: ["keep-the-commandments", "keeping-laws-in-present-world", "law-and-commandment-the-same", "law-not-void-through-our-faith", "laws-from-the-beginning", "laws-of-the-land", "no-commandments-no-kingdom"] },
      { week: 45, topicKeys: ["order", "order-decently-and-in-order", "out-of-order", "plead-sword-war", "sex-laws", "sovereign", "swearing-snitching", "sword", "teaching-children-commandments", "the-law"] },
      { week: 46, topicKeys: ["tithe", "voting"] },
    ],
  },
  {
    id: "ceremonial-law",
    title: "Ceremonial Law",
    description: "Feasts, Sabbath, circumcision, and ritual worship.",
    startWeek: 47,
    endWeek: 52,
    weeks: [
      { week: 47, topicKeys: ["ark-of-the-covenant", "baptism", "circumcision", "day-of-atonement"] },
      { week: 48, topicKeys: ["high-holy-days-day-of-atonement", "eat-sacrifice", "feast-of-dedication", "feast-of-tabernacles", "high-holy-days", "high-holy-days-feast-of-tabernacles"] },
      { week: 49, topicKeys: ["high-holy-days-memorial-of-blowing-of-trumpets", "high-holy-days-new-moon"] },
      { week: 50, topicKeys: ["high-holy-days-passover", "high-holy-days-pentecost", "high-holy-days-purim"] },
      { week: 51, topicKeys: ["sabbath", "months-comes-from-moon", "moon-does-not-dictate-sabbath", "new-moon-does-not-determine-the-sabbath", "sacrificial-law-is-dead"] },
      { week: 52, topicKeys: ["sex-with-your-wife-when-she-is-on-her-issue-of-blood", "table", "traditions-and-pagan-holidays", "high-holy-days-feast-of-dedication"] },
    ],
  },
  {
    id: "dietary-law",
    title: "Dietary Law",
    description: "The laws of clean and unclean food.",
    startWeek: 53,
    endWeek: 53,
    weeks: [
      { week: 53, topicKeys: ["clean", "clean-food", "cleanse", "dietary-laws"] },
    ],
  },
  {
    id: "godhead-and-christ",
    title: "The Godhead & Christ",
    description: "The nature of God and the identity of Christ.",
    startWeek: 54,
    endWeek: 60,
    weeks: [
      { week: 54, topicKeys: ["another-jesus", "christ-came-for-israel", "christ-did-not-baptize-with-water", "christ-freed-us-from-the-law-of-sin-and-death", "christ-from-the-tribe-of-judah", "christ-fulfilled", "christ-had-an-earthly-father"] },
      { week: 55, topicKeys: ["christ-in-roman-captivity", "christ-in-the-apocrypha", "christ-in-the-old-testament", "christ-is-not-the-father", "christ-justifies-israel-only"] },
      { week: 56, topicKeys: ["christ-return", "christ-taught-repentance", "christ-told-us-not-to-sin", "christ-was-not-soft", "christ-who-rejected-him", "color-of-christ"] },
      { week: 57, topicKeys: ["fallen-angels", "foreknew-god", "god-dealing-with-the-mixed-multitude", "god-does-evil", "god-does-have-respect-of-persons", "god-does-not-hear-sinners"] },
      { week: 58, topicKeys: ["god-gives-recompense-and-revenge", "god-hates", "god-is-a-man", "god-is-black"] },
      { week: 59, topicKeys: ["god-loves-israel", "god-must-deal-with-the-southern-judah-kingdom-first", "god-pleads-with-the-nations", "god-puts-difference-between-the-children-of-israel-and-ham", "gods-favorites", "gods-people", "gods-way-question-him", "holy-ghost"] },
      { week: 60, topicKeys: ["holy-spirit", "how-do-we-know-that-we-know-god", "jesus-had-a-home", "jesus-means", "manner-of-christ", "name-of-god"] },
    ],
  },
  {
    id: "discerning-truth",
    title: "Discerning Truth",
    description: "False prophets, idols, and other religions compared.",
    startWeek: 61,
    endWeek: 65,
    weeks: [
      { week: 61, topicKeys: ["catholicism", "christmas-is-not-of-christ", "fake-jews-jewish", "false-christ", "false-prophet"] },
      { week: 62, topicKeys: ["idolatry", "images-changed", "images-goodly", "images-worship"] },
      { week: 63, topicKeys: ["immaculate-conception-lie", "infidel", "islam-created-in-622-ad", "koran"] },
      { week: 64, topicKeys: ["rasta", "spells-and-enchantments-on-jacob", "spiritual-idolatry", "trinity", "true-witness-jehovah-witness"] },
      { week: 65, topicKeys: ["ufo-ufos-are-chariots", "witch-witchcraft-magic-star-gazing"] },
    ],
  },
  {
    id: "holiness-and-appearance",
    title: "Holiness & Appearance",
    description: "Dress, hair, and outward holiness.",
    startWeek: 66,
    endWeek: 69,
    weeks: [
      { week: 66, topicKeys: ["apparel", "appearance", "beard", "blonde-hair-is-unclean", "braids", "dress-code-for-women"] },
      { week: 67, topicKeys: ["dress-code-fringes", "earrings", "eyes-red-with-wine", "hair-texture", "head-covering-men", "head-covering-women"] },
      { week: 68, topicKeys: ["how-to-dress", "known-by-his-look", "linen-breeches", "loin-gird-up", "long-hair-men", "purple-royalist", "strange-apparel", "tattoos"] },
      { week: 69, topicKeys: ["women-cant-wear-pants", "modesty-dress", "wooly-hair"] },
    ],
  },
  {
    id: "sin-repentance-and-salvation",
    title: "Sin, Repentance & Salvation",
    description: "Sin, repentance, grace, and salvation.",
    startWeek: 70,
    endWeek: 74,
    weeks: [
      { week: 70, topicKeys: ["abortion", "adultery", "born-again", "born-gay", "cover-up-sin"] },
      { week: 71, topicKeys: ["homosexual-gay", "john-told-us-not-to-sin", "lust", "new-creature", "paul-told-us-not-to-sin", "rape-is-a-sin"] },
      { week: 72, topicKeys: ["regeneration", "repent-or-die", "repentance-according-to-the-bible", "repentance-is-only-for-israel"] },
      { week: 73, topicKeys: ["salvation-for-israel", "sexual-sins", "show-our-people-their-sins", "sickness-from-sin-and-healing"] },
      { week: 74, topicKeys: ["sin", "sinner", "sodom-spirit", "solomons-sin", "wages-of-sin", "whoredom-physical", "whoredom-spiritual"] },
    ],
  },
  {
    id: "family-life",
    title: "Family Life",
    description: "Marriage, children, and household roles.",
    startWeek: 75,
    endWeek: 80,
    weeks: [
      { week: 75, topicKeys: ["adoption", "birth-of-a-boy", "birth-of-a-girl", "children-raising-kids", "daughters"] },
      { week: 76, topicKeys: ["divorce", "family-according-to-the-bible", "firstborn-heir", "good-wife"] },
      { week: 77, topicKeys: ["interracial-marriage", "labor-pains-were-created", "man-must-rule-his-household", "man-show-thyself-a-man"] },
      { week: 78, topicKeys: ["marriage", "marriage-papers"] },
      { week: 79, topicKeys: ["marriage-to-other-nations", "marriageable-age", "men-need-to-work", "multiple-wives"] },
      { week: 80, topicKeys: ["order-of-man-and-woman", "order-of-women", "seed-comes-from-the-man", "take-wives-and-build-a-nation", "wicked-women", "woman-cannot-divorce-her-husband", "woman-must-submit-to-husband", "woman-learn-from"] },
    ],
  },
  {
    id: "the-hope-ahead",
    title: "The Hope Ahead",
    description: "Judgment, the last days, and studying scripture.",
    startWeek: 81,
    endWeek: 86,
    weeks: [
      { week: 81, topicKeys: ["book-of-life", "book-of-the-dead", "bottomless-pit", "eternal-life", "heaven", "heaven-how-to-get-in", "hell", "judge-we-can-judge"] },
      { week: 82, topicKeys: ["mark-of-the-beast", "tribulation", "all-knowledge-given-to-israel", "bible-author"] },
      { week: 83, topicKeys: ["how-to-read", "bible-only-for-israel", "bible-true-book"] },
      { week: 84, topicKeys: ["dark-sayings-and-parables", "doctrine", "knowledge", "prove", "pure-language", "study"] },
      { week: 85, topicKeys: ["study-whole-bible", "the-names", "tongues"] },
      { week: 86, topicKeys: ["truth", "who-wrote-the-bible", "word-word-is-pure"] },
    ],
  },
];

export const WEEKLY_STUDY_PLAN_TOTAL_WEEKS =
  WEEKLY_STUDY_PLAN[WEEKLY_STUDY_PLAN.length - 1].endWeek;
